spring:
    application:
        name: client
    security:
        oauth2:
            client:
                registration:
                    keycloak-client:
                        client-id: oauth2-client-credentials
                        client-secret: b7vAkp8nBRZFEsSfCzuxytZ6kmmbM9eG
                        scope: openid
                        authorization-grant-type: client_credentials
                provider:
                    keycloak-client:
                        token-uri: http://127.0.0.1:8443/realms/oauth2-demos/protocol/openid-connect/token
            resourceserver:
                jwt:
                    issuer-uri: http://127.0.0.1:8443/realms/oauth2-demos

resource-server:
    url: http://localhost:8082
