#spring.application.name=store
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
spring:
  application:
    name: store
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: beans, health
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: Store
    description: App built by us
    version: 1.0.0
