spring:
    application:
        name: config-server
    profiles:
        active: native ## Specify profile because by default it tries to use git
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config ##May not dynamically update on refreshes since the classes are bundled on initial startup. Youcan also use file as shown below
                    #search-locations: file:///C:\Users\malco\OneDrive\Desktop\Coding\java\store\config-server\src\main\resources\config
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: guest
#        password: guest

management:
    endpoints:
        web:
            exposure:
                include: "*"

server:
    port: 8888

#encrypt:
#    key-store:
#        location: config-server.jks
#        password: mypass
#        alias: config-server-key
