spring:
    #    h2:
    #        console:
    #            enabled: true
    #    datasource:
    #        url: jdbc:h2:mem:test
    #    jpa:
    #        show-sql: true
    #        hibernate:
    #            ddl-auto: create
    #    datasource:
    #        url: jdbc:postgresql://localhost:5432/userdb
    #        username: malcolm
    #        password: malcolm
    #
    #    jpa:
    #        database: POSTGRESQL
    #        show-sql: true
    #        hibernate:
    #            ddl-auto: create
    #        database-platform: org.hibernate.dialect.PostgreSQLDialect
    data:
        mongodb:
            uri: ${MONGODB_URI:?MONGODB_URI is required}
            database: userdb

server:
    port: 8082
