spring:
    application:
        name: consumer
    #    kafka:
    #        consumer:
    #            bootstrap-servers: localhost:9092
    #            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    #            properties:
    #                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    #                spring.json.trusted.packages: "*"
    #                spring.json.value.default.type: com.store.demo.kafka.consumer.RiderLocation
    cloud:
        stream:
            function:
                definition: processRiderLocation
            bindings:
                processRiderLocation-in-0:
                    destination: my-topic-new
                    content-type: application/json
            kafka:
                binders:
                    brokers: localhost:9092

server:
    port: 8081
